/*
Deployment script for TEAM5DB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "TEAM5DB"
:setvar DefaultFilePrefix "TEAM5DB"
:setvar DefaultDataPath "C:\Users\hengm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\hengm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating database $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS OFF,
                ANSI_PADDING OFF,
                ANSI_WARNINGS OFF,
                ARITHABORT OFF,
                CONCAT_NULL_YIELDS_NULL OFF,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER OFF,
                ANSI_NULL_DEFAULT OFF,
                CURSOR_DEFAULT GLOBAL,
                RECOVERY SIMPLE,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK ON,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY CHECKSUM,
                DATE_CORRELATION_OPTIMIZATION OFF,
                ENABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 60 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF),
                MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = OFF,
                DELAYED_DURABILITY = DISABLED 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE = OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET TEMPORAL_HISTORY_RETENTION ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating Table [dbo].[tbAdjustment]...';


GO
CREATE TABLE [dbo].[tbAdjustment] (
    [id]          INT          IDENTITY (1, 1) NOT NULL,
    [referenceno] VARCHAR (50) NULL,
    [pcode]       VARCHAR (50) NULL,
    [qty]         INT          NULL,
    [action]      VARCHAR (50) NULL,
    [remarks]     VARCHAR (50) NULL,
    [sdate]       DATE         NULL,
    [user]        VARCHAR (50) NULL,
    CONSTRAINT [PK_tbAdjustment] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbBrand]...';


GO
CREATE TABLE [dbo].[tbBrand] (
    [id]    INT          IDENTITY (1, 1) NOT NULL,
    [brand] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_tbBrand] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbCancel]...';


GO
CREATE TABLE [dbo].[tbCancel] (
    [id]          INT             IDENTITY (1, 1) NOT NULL,
    [transno]     VARCHAR (50)    NULL,
    [pcode]       VARCHAR (50)    NULL,
    [price]       DECIMAL (18, 2) NULL,
    [qty]         INT             NULL,
    [total]       DECIMAL (18, 2) NULL,
    [sdate]       DATE            NULL,
    [voidby]      VARCHAR (50)    NULL,
    [cancelledby] VARCHAR (50)    NULL,
    [reason]      TEXT            NULL,
    [action]      VARCHAR (50)    NULL,
    CONSTRAINT [PK_tbCancel] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbCart]...';


GO
CREATE TABLE [dbo].[tbCart] (
    [id]           INT             IDENTITY (1, 1) NOT NULL,
    [transno]      VARCHAR (50)    NULL,
    [pcode]        VARCHAR (50)    NULL,
    [price]        DECIMAL (18, 2) NULL,
    [qty]          INT             NULL,
    [disc_percent] DECIMAL (18, 2) NULL,
    [disc]         DECIMAL (18, 2) NULL,
    [total]        DECIMAL (18, 2) NULL,
    [sdate]        DATE            NULL,
    [status]       VARCHAR (50)    NULL,
    [cashier]      VARCHAR (50)    NULL,
    CONSTRAINT [PK_tbCart] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbCategory]...';


GO
CREATE TABLE [dbo].[tbCategory] (
    [id]       INT          IDENTITY (1, 1) NOT NULL,
    [category] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_tbCategory] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbProduct]...';


GO
CREATE TABLE [dbo].[tbProduct] (
    [pcode]   VARCHAR (50)    NOT NULL,
    [barcode] VARCHAR (50)    NULL,
    [pdesc]   VARCHAR (MAX)   NOT NULL,
    [bid]     INT             NOT NULL,
    [cid]     INT             NOT NULL,
    [price]   DECIMAL (18, 2) NOT NULL,
    [qty]     INT             NULL,
    [reorder] INT             NULL,
    CONSTRAINT [PK_tbProduct_1] PRIMARY KEY CLUSTERED ([pcode] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbStockIn]...';


GO
CREATE TABLE [dbo].[tbStockIn] (
    [id]         INT          IDENTITY (1, 1) NOT NULL,
    [refno]      VARCHAR (50) NULL,
    [pcode]      VARCHAR (50) NULL,
    [qty]        INT          NULL,
    [sdate]      DATETIME     NULL,
    [stockinby]  VARCHAR (50) NULL,
    [status]     VARCHAR (50) NULL,
    [supplierid] INT          NULL,
    CONSTRAINT [PK_tbStockIn_1] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbStore]...';


GO
CREATE TABLE [dbo].[tbStore] (
    [store]   VARCHAR (50)  NOT NULL,
    [address] VARCHAR (MAX) NULL
);


GO
PRINT N'Creating Table [dbo].[tbSupplier]...';


GO
CREATE TABLE [dbo].[tbSupplier] (
    [id]            INT          IDENTITY (1, 1) NOT NULL,
    [supplier]      VARCHAR (50) NOT NULL,
    [address]       TEXT         NOT NULL,
    [contactperson] VARCHAR (50) NOT NULL,
    [phone]         VARCHAR (50) NOT NULL,
    [email]         VARCHAR (50) NOT NULL,
    [fax]           VARCHAR (50) NULL,
    CONSTRAINT [PK_tbSupplier_1] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[tbUser]...';


GO
CREATE TABLE [dbo].[tbUser] (
    [username]   VARCHAR (50) NOT NULL,
    [password]   VARCHAR (50) NOT NULL,
    [role]       VARCHAR (50) NOT NULL,
    [name]       VARCHAR (50) NOT NULL,
    [isactivate] VARCHAR (50) NULL,
    CONSTRAINT [PK_tbUser] PRIMARY KEY CLUSTERED ([username] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbCart_disc]...';


GO
ALTER TABLE [dbo].[tbCart]
    ADD CONSTRAINT [DF_tbCart_disc] DEFAULT ((0)) FOR [disc];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbCart_disc_percent]...';


GO
ALTER TABLE [dbo].[tbCart]
    ADD CONSTRAINT [DF_tbCart_disc_percent] DEFAULT ((0)) FOR [disc_percent];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbCart_qty]...';


GO
ALTER TABLE [dbo].[tbCart]
    ADD CONSTRAINT [DF_tbCart_qty] DEFAULT ((0)) FOR [qty];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbCart_status]...';


GO
ALTER TABLE [dbo].[tbCart]
    ADD CONSTRAINT [DF_tbCart_status] DEFAULT ('Pending') FOR [status];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbProduct_qty]...';


GO
ALTER TABLE [dbo].[tbProduct]
    ADD CONSTRAINT [DF_tbProduct_qty] DEFAULT ((0)) FOR [qty];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbStockIn_qty]...';


GO
ALTER TABLE [dbo].[tbStockIn]
    ADD CONSTRAINT [DF_tbStockIn_qty] DEFAULT ((0)) FOR [qty];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbStockIn_status]...';


GO
ALTER TABLE [dbo].[tbStockIn]
    ADD CONSTRAINT [DF_tbStockIn_status] DEFAULT ('Pending') FOR [status];


GO
PRINT N'Creating Default Constraint [dbo].[DF_tbUser_isactive]...';


GO
ALTER TABLE [dbo].[tbUser]
    ADD CONSTRAINT [DF_tbUser_isactive] DEFAULT ('True') FOR [isactivate];


GO
PRINT N'Creating Foreign Key [dbo].[FK_tbCart_tbProduct]...';


GO
ALTER TABLE [dbo].[tbCart]
    ADD CONSTRAINT [FK_tbCart_tbProduct] FOREIGN KEY ([pcode]) REFERENCES [dbo].[tbProduct] ([pcode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tbProduct_tbBrand]...';


GO
ALTER TABLE [dbo].[tbProduct]
    ADD CONSTRAINT [FK_tbProduct_tbBrand] FOREIGN KEY ([bid]) REFERENCES [dbo].[tbBrand] ([id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tbStockIn_tbProduct]...';


GO
ALTER TABLE [dbo].[tbStockIn]
    ADD CONSTRAINT [FK_tbStockIn_tbProduct] FOREIGN KEY ([pcode]) REFERENCES [dbo].[tbProduct] ([pcode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tbStockIn_tbSupplier]...';


GO
ALTER TABLE [dbo].[tbStockIn]
    ADD CONSTRAINT [FK_tbStockIn_tbSupplier] FOREIGN KEY ([supplierid]) REFERENCES [dbo].[tbSupplier] ([id]);


GO
PRINT N'Creating Trigger [dbo].[ComputTotal]...';


GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE TRIGGER [dbo].[ComputTotal]
   ON [dbo].[tbCart]
   AFTER INSERT,DELETE,UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON
	update tbCart SET disc = ((price*qty) * disc_percent *  0.01)
	update tbCart SET total = (price*qty)-disc

    -- Insert statements for trigger here

END
GO
PRINT N'Creating View [dbo].[vwCancelItems]...';


GO
CREATE VIEW dbo.vwCancelItems
AS
SELECT        dbo.tbCancel.transno, dbo.tbCancel.pcode, dbo.tbProduct.pdesc, 
                         dbo.tbCancel.price, dbo.tbCancel.qty, dbo.tbCancel.total, dbo.tbCancel.sdate, 
                         dbo.tbCancel.voidby, dbo.tbCancel.cancelledby, dbo.tbCancel.reason, 
                         dbo.tbCancel.action
FROM            dbo.tbCancel INNER JOIN
                         dbo.tbProduct ON dbo.tbCancel.pcode = dbo.tbProduct.pcode
GO
PRINT N'Creating View [dbo].[vwCriticalItems]...';


GO
CREATE VIEW dbo.vwCriticalItems
AS
SELECT        dbo.tbProduct.pcode, dbo.tbProduct.barcode, dbo.tbProduct.pdesc, 
                         dbo.tbBrand.brand, dbo.tbCategory.category, dbo.tbProduct.price, 
                         dbo.tbProduct.reorder, dbo.tbProduct.qty
FROM            dbo.tbProduct INNER JOIN
                         dbo.tbCategory ON dbo.tbProduct.cid = dbo.tbCategory.id INNER JOIN
                         dbo.tbBrand ON dbo.tbProduct.bid = dbo.tbBrand.id
WHERE        (dbo.tbProduct.qty <= dbo.tbProduct.reorder)
GO
PRINT N'Creating View [dbo].[vwInventoryList]...';


GO
CREATE VIEW dbo.vwInventoryList
AS
SELECT        dbo.tbProduct.pcode, dbo.tbProduct.barcode, dbo.tbProduct.pdesc, 
                         dbo.tbBrand.brand, dbo.tbCategory.category, dbo.tbProduct.price, 
                         dbo.tbProduct.qty, dbo.tbProduct.reorder
FROM            dbo.tbProduct INNER JOIN
                         dbo.tbCategory ON dbo.tbProduct.cid = dbo.tbCategory.id INNER JOIN
                         dbo.tbBrand ON dbo.tbProduct.bid = dbo.tbBrand.id
GO
PRINT N'Creating View [dbo].[vwStockIn]...';


GO
CREATE VIEW dbo.vwStockIn
AS
SELECT        dbo.tbStockIn.id, dbo.tbStockIn.refno, dbo.tbStockIn.pcode, dbo.tbProduct.pdesc, 
                         dbo.tbStockIn.qty, dbo.tbStockIn.sdate, dbo.tbStockIn.stockinby, 
                         dbo.tbStockIn.status, dbo.tbSupplier.supplier
FROM            dbo.tbProduct INNER JOIN
                         dbo.tbStockIn ON dbo.tbProduct.pcode = dbo.tbStockIn.pcode INNER JOIN
                         dbo.tbSupplier ON dbo.tbStockIn.supplierid = dbo.tbSupplier.id
GO
PRINT N'Creating View [dbo].[vwTopSelling]...';


GO
CREATE VIEW dbo.[vwTopSelling]
AS
SELECT        dbo.tbCart.pcode, dbo.tbProduct.pdesc, dbo.tbCart.qty, dbo.tbCart.sdate, 
                         dbo.tbCart.total, dbo.tbCart.status
FROM            dbo.tbCart INNER JOIN
                         dbo.tbProduct ON dbo.tbCart.pcode = dbo.tbProduct.pcode
GO
PRINT N'Creating Extended Property [dbo].[vwCancelItems].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[16] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "tbCancel"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 268
               Right = 206
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tbProduct"
            Begin Extent = 
               Top = 6
               Left = 244
               Bottom = 141
               Right = 412
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 11
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwCancelItems';


GO
PRINT N'Creating Extended Property [dbo].[vwCancelItems].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwCancelItems';


GO
PRINT N'Creating Extended Property [dbo].[vwCriticalItems].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[42] 4[11] 2[19] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "tbBrand"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 105
               Right = 206
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tbCategory"
            Begin Extent = 
               Top = 6
               Left = 244
               Bottom = 105
               Right = 412
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tbProduct"
            Begin Extent = 
               Top = 153
               Left = 252
               Bottom = 288
               Right = 420
            End
            DisplayFlags = 280
            TopColumn = 4
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwCriticalItems';


GO
PRINT N'Creating Extended Property [dbo].[vwCriticalItems].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwCriticalItems';


GO
PRINT N'Creating Extended Property [dbo].[vwInventoryList].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "tbBrand"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 105
               Right = 206
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tbCategory"
            Begin Extent = 
               Top = 13
               Left = 430
               Bottom = 112
               Right = 598
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tbProduct"
            Begin Extent = 
               Top = 164
               Left = 231
               Bottom = 299
               Right = 399
            End
            DisplayFlags = 280
            TopColumn = 4
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwInventoryList';


GO
PRINT N'Creating Extended Property [dbo].[vwInventoryList].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwInventoryList';


GO
PRINT N'Creating Extended Property [dbo].[vwStockIn].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[12] 2[29] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "tbProduct"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 141
               Right = 206
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tbStockIn"
            Begin Extent = 
               Top = 6
               Left = 244
               Bottom = 141
               Right = 412
            End
            DisplayFlags = 280
            TopColumn = 4
         End
         Begin Table = "tbSupplier"
            Begin Extent = 
               Top = 6
               Left = 450
               Bottom = 141
               Right = 618
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 10
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwStockIn';


GO
PRINT N'Creating Extended Property [dbo].[vwStockIn].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwStockIn';


GO
PRINT N'Creating Extended Property [dbo].[vwTopSelling].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[15] 2[15] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "tbCart"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 230
               Right = 206
            End
            DisplayFlags = 280
            TopColumn = 2
         End
         Begin Table = "tbProduct"
            Begin Extent = 
               Top = 6
               Left = 244
               Bottom = 241
               Right = 412
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwTopSelling';


GO
PRINT N'Creating Extended Property [dbo].[vwTopSelling].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vwTopSelling';


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
